######################################################################
# Automatically generated by qmake (2.01a) Di Aug 28 22:17:09 2007
######################################################################

TEMPLATE = app
TARGET = ../../qcreate
DEPENDPATH += .
INCLUDEPATH += .
QT = core sql

# Input
SOURCES += main.cpp
