######################################################################
# Automatically generated by qmake (2.01a) Mo Aug 27 21:20:40 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT = core network

# Input
SOURCES += main.cpp
