######################################################################
# Automatically generated by qmake (2.01a) Mo Aug 27 19:15:33 2007
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT = core network sql

# Input
HEADERS += client.h fetcher.h server.h graph.h
SOURCES += client.cpp fetcher.cpp main.cpp server.cpp
